# CMAKE generated file: DO NOT EDIT!
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by "Unix Makefiles" Generator, CMake Version 3.28
=======
# Generated by "Unix Makefiles" Generator, CMake Version 3.26
>>>>>>> 6bb2e7a (add CGAL mesh functionality)
=======
# Generated by "Unix Makefiles" Generator, CMake Version 3.26
>>>>>>> 40274453b0eae72feed463be84f86d0ba2006db0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
<<<<<<< HEAD
<<<<<<< HEAD
CMAKE_COMMAND = /opt/homebrew/lib/python3.11/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/lib/python3.11/site-packages/cmake/data/bin/cmake -E rm -f
=======
=======
>>>>>>> 40274453b0eae72feed463be84f86d0ba2006db0
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f
<<<<<<< HEAD
>>>>>>> 6bb2e7a (add CGAL mesh functionality)
=======
>>>>>>> 40274453b0eae72feed463be84f86d0ba2006db0

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
<<<<<<< HEAD
<<<<<<< HEAD
CMAKE_SOURCE_DIR = /Users/juliaisaac/Suture-Placement

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/juliaisaac/Suture-Placement
=======
=======
>>>>>>> 40274453b0eae72feed463be84f86d0ba2006db0
CMAKE_SOURCE_DIR = /Users/virajramakrishnan/Desktop/Uni/AUTOLab/Suture-Placement

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/virajramakrishnan/Desktop/Uni/AUTOLab/Suture-Placement
<<<<<<< HEAD
>>>>>>> 6bb2e7a (add CGAL mesh functionality)
=======
>>>>>>> 40274453b0eae72feed463be84f86d0ba2006db0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
<<<<<<< HEAD
<<<<<<< HEAD
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/lib/python3.11/site-packages/cmake/data/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
=======
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
>>>>>>> 6bb2e7a (add CGAL mesh functionality)
=======
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
>>>>>>> 40274453b0eae72feed463be84f86d0ba2006db0
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
<<<<<<< HEAD
<<<<<<< HEAD
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/lib/python3.11/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
=======
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
>>>>>>> 6bb2e7a (add CGAL mesh functionality)
=======
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
>>>>>>> 40274453b0eae72feed463be84f86d0ba2006db0
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
<<<<<<< HEAD
<<<<<<< HEAD
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/juliaisaac/Suture-Placement/CMakeFiles /Users/juliaisaac/Suture-Placement//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/juliaisaac/Suture-Placement/CMakeFiles 0
=======
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/virajramakrishnan/Desktop/Uni/AUTOLab/Suture-Placement/CMakeFiles /Users/virajramakrishnan/Desktop/Uni/AUTOLab/Suture-Placement//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/virajramakrishnan/Desktop/Uni/AUTOLab/Suture-Placement/CMakeFiles 0
>>>>>>> 6bb2e7a (add CGAL mesh functionality)
=======
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/virajramakrishnan/Desktop/Uni/AUTOLab/Suture-Placement/CMakeFiles /Users/virajramakrishnan/Desktop/Uni/AUTOLab/Suture-Placement//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/virajramakrishnan/Desktop/Uni/AUTOLab/Suture-Placement/CMakeFiles 0
>>>>>>> 40274453b0eae72feed463be84f86d0ba2006db0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named generate_mesh

# Build rule for target.
generate_mesh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_mesh
.PHONY : generate_mesh

# fast build rule for target.
generate_mesh/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_mesh.dir/build.make CMakeFiles/generate_mesh.dir/build
.PHONY : generate_mesh/fast

generate_mesh.o: generate_mesh.cpp.o
.PHONY : generate_mesh.o

# target to build an object file
generate_mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_mesh.dir/build.make CMakeFiles/generate_mesh.dir/generate_mesh.cpp.o
.PHONY : generate_mesh.cpp.o

generate_mesh.i: generate_mesh.cpp.i
.PHONY : generate_mesh.i

# target to preprocess a source file
generate_mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_mesh.dir/build.make CMakeFiles/generate_mesh.dir/generate_mesh.cpp.i
.PHONY : generate_mesh.cpp.i

generate_mesh.s: generate_mesh.cpp.s
.PHONY : generate_mesh.s

# target to generate assembly for a file
generate_mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_mesh.dir/build.make CMakeFiles/generate_mesh.dir/generate_mesh.cpp.s
.PHONY : generate_mesh.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... generate_mesh"
	@echo "... generate_mesh.o"
	@echo "... generate_mesh.i"
	@echo "... generate_mesh.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

